"""add withholding certificates

Revision ID: 0fe42c8a0fa3
Revises: 19bd77c95747
Create Date: 2026-02-16 14:52:45.799546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe42c8a0fa3'
down_revision = '19bd77c95747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withholding_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('doc_no', sa.String(length=40), nullable=False),
    sa.Column('payee_kind', sa.String(length=10), nullable=False),
    sa.Column('payee_person_id', sa.Integer(), nullable=True),
    sa.Column('payee_entity_id', sa.Integer(), nullable=True),
    sa.Column('payer_name', sa.String(length=200), nullable=False),
    sa.Column('payer_tax_id', sa.String(length=40), nullable=True),
    sa.Column('payer_address', sa.Text(), nullable=True),
    sa.Column('payer_branch_no', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('income_type', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wht_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('wht_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(payee_kind='PERSON' AND payee_person_id IS NOT NULL AND payee_entity_id IS NULL) OR (payee_kind='ENTITY' AND payee_entity_id IS NOT NULL AND payee_person_id IS NULL)", name='ck_wht_cert_payee_one_of'),
    sa.CheckConstraint('base_amount >= 0', name='ck_wht_cert_base_nonneg'),
    sa.CheckConstraint('wht_amount >= 0', name='ck_wht_cert_amount_nonneg'),
    sa.CheckConstraint('wht_rate >= 0', name='ck_wht_cert_rate_nonneg'),
    sa.ForeignKeyConstraint(['payee_entity_id'], ['withholding_entities.id'], ),
    sa.ForeignKeyConstraint(['payee_person_id'], ['withholding_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withholding_certificates', schema=None) as batch_op:
        batch_op.create_index('ix_wht_cert_form_type', ['form_type'], unique=False)
        batch_op.create_index('ix_wht_cert_payment_date', ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_certificates_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_withholding_certificates_form_type'), ['form_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_certificates_payee_entity_id'), ['payee_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_certificates_payee_kind'), ['payee_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_certificates_payee_person_id'), ['payee_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_certificates_payment_date'), ['payment_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withholding_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withholding_certificates_payment_date'))
        batch_op.drop_index(batch_op.f('ix_withholding_certificates_payee_person_id'))
        batch_op.drop_index(batch_op.f('ix_withholding_certificates_payee_kind'))
        batch_op.drop_index(batch_op.f('ix_withholding_certificates_payee_entity_id'))
        batch_op.drop_index(batch_op.f('ix_withholding_certificates_form_type'))
        batch_op.drop_index(batch_op.f('ix_withholding_certificates_doc_no'))
        batch_op.drop_index('ix_wht_cert_payment_date')
        batch_op.drop_index('ix_wht_cert_form_type')

    op.drop_table('withholding_certificates')
    # ### end Alembic commands ###
