"""add withholding people and entities

Revision ID: 19bd77c95747
Revises: a7768ce0fa31
Create Date: 2026-02-15 13:20:52.036037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bd77c95747'
down_revision = 'a7768ce0fa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withholding_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('person_type', sa.String(length=30), nullable=False),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withholding_people', schema=None) as batch_op:
        batch_op.create_index('ix_wht_people_full_name', ['full_name'], unique=False)
        batch_op.create_index('ix_wht_people_person_type', ['person_type'], unique=False)
        batch_op.create_index('ix_wht_people_tax_id', ['tax_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_people_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_people_person_type'), ['person_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_people_tax_id'), ['tax_id'], unique=False)

    op.create_table('withholding_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withholding_entities', schema=None) as batch_op:
        batch_op.create_index('ix_wht_entities_company_name', ['company_name'], unique=False)
        batch_op.create_index('ix_wht_entities_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_wht_entities_tax_id', ['tax_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_entities_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_entities_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withholding_entities_tax_id'), ['tax_id'], unique=False)

    with op.batch_alter_table('sales_docs', schema=None) as batch_op:
        batch_op.alter_column('customer_email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_docs', schema=None) as batch_op:
        batch_op.alter_column('customer_email',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('withholding_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withholding_entities_tax_id'))
        batch_op.drop_index(batch_op.f('ix_withholding_entities_customer_id'))
        batch_op.drop_index(batch_op.f('ix_withholding_entities_company_name'))
        batch_op.drop_index('ix_wht_entities_tax_id')
        batch_op.drop_index('ix_wht_entities_customer_id')
        batch_op.drop_index('ix_wht_entities_company_name')

    op.drop_table('withholding_entities')
    with op.batch_alter_table('withholding_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withholding_people_tax_id'))
        batch_op.drop_index(batch_op.f('ix_withholding_people_person_type'))
        batch_op.drop_index(batch_op.f('ix_withholding_people_full_name'))
        batch_op.drop_index('ix_wht_people_tax_id')
        batch_op.drop_index('ix_wht_people_person_type')
        batch_op.drop_index('ix_wht_people_full_name')

    op.drop_table('withholding_people')
    # ### end Alembic commands ###
