"""add tax invoice fields to material_items

Revision ID: 3027f74a75f7
Revises: 0fe42c8a0fa3
Create Date: 2026-02-18 17:14:07.008708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3027f74a75f7'
down_revision = '0fe42c8a0fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_invoice_no', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('tax_invoice_date', sa.Date(), nullable=True))
        batch_op.create_index('ix_material_items_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_material_items_tax_invoice_date', ['tax_invoice_date'], unique=False)
        batch_op.create_index('ix_material_items_tax_invoice_no', ['tax_invoice_no'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('materials_tax_invoice_no')
        batch_op.drop_column('materials_tax_invoice_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials_tax_invoice_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('materials_tax_invoice_no', sa.VARCHAR(length=60), autoincrement=False, nullable=True))

    with op.batch_alter_table('material_items', schema=None) as batch_op:
        batch_op.drop_index('ix_material_items_tax_invoice_no')
        batch_op.drop_index('ix_material_items_tax_invoice_date')
        batch_op.drop_index('ix_material_items_project_id')
        batch_op.drop_column('tax_invoice_date')
        batch_op.drop_column('tax_invoice_no')

    # ### end Alembic commands ###
