"""init

Revision ID: 72e596dd2ce1
Revises: 
Create Date: 2026-01-20 15:20:22.239061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e596dd2ce1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('work_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('work_days >= 0', name='ck_projects_work_days_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_code', ['code'], unique=False)
        batch_op.create_index('ix_projects_name', ['name'], unique=False)

    op.create_table('material_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('item_code', sa.String(length=80), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('qty >= 0', name='ck_material_qty_nonneg'),
    sa.CheckConstraint('unit_price >= 0', name='ck_material_unit_price_nonneg'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_other_amount_nonneg'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_expenses', schema=None) as batch_op:
        batch_op.create_index('ix_other_expenses_category', ['category'], unique=False)

    op.create_table('subcontractor_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('contract_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('withholding_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('withholding_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('contract_amount >= 0', name='ck_sub_contract_amount_nonneg'),
    sa.CheckConstraint('withholding_amount >= 0', name='ck_sub_wht_amount_nonneg'),
    sa.CheckConstraint('withholding_rate >= 0', name='ck_sub_wht_rate_nonneg'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcontractor_payments')
    with op.batch_alter_table('other_expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_other_expenses_category')

    op.drop_table('other_expenses')
    op.drop_table('material_items')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_name')
        batch_op.drop_index('ix_projects_code')

    op.drop_table('projects')
    # ### end Alembic commands ###
