"""add advances and new date fields

Revision ID: a7768ce0fa31
Revises: a711ca143cfb
Create Date: 2026-02-14 13:25:11.900093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7768ce0fa31'
down_revision = 'a711ca143cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advance_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('advance_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_advance_amount_nonneg'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advance_expenses', schema=None) as batch_op:
        batch_op.create_index('ix_advance_expenses_project_id', ['project_id'], unique=False)

    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('other_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_date', sa.Date(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials_tax_invoice_no', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('materials_tax_invoice_date', sa.Date(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_projects_sales_doc_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_projects_sales_doc_id'), ['sales_doc_id'], unique=True)
        batch_op.drop_constraint(batch_op.f('fk_projects_sales_doc_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sales_docs', ['sales_doc_id'], ['id'])

    with op.batch_alter_table('sales_docs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_sales_docs_doc_type'))
        batch_op.drop_index(batch_op.f('ix_sales_docs_status'))
        batch_op.drop_index(batch_op.f('ux_sales_docs_doc_no'))
        batch_op.create_index(batch_op.f('ix_sales_docs_doc_no'), ['doc_no'], unique=True)
        batch_op.drop_constraint(batch_op.f('fk_sales_docs_customer_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_docs_parent'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'sales_docs', ['parent_id'], ['id'])

    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_sales_items_doc'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sales_docs', ['doc_id'], ['id'])

    with op.batch_alter_table('subcontractor_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcontractor_payments', schema=None) as batch_op:
        batch_op.drop_column('pay_date')

    with op.batch_alter_table('sales_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sales_items_doc'), 'sales_docs', ['doc_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('sales_docs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sales_docs_parent'), 'sales_docs', ['parent_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_sales_docs_customer_id'), 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_sales_docs_doc_no'))
        batch_op.create_index(batch_op.f('ux_sales_docs_doc_no'), ['doc_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_docs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_docs_doc_type'), ['doc_type'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_projects_sales_doc_id'), 'sales_docs', ['sales_doc_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_projects_sales_doc_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_projects_sales_doc_id'), ['sales_doc_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('materials_tax_invoice_date')
        batch_op.drop_column('materials_tax_invoice_no')

    with op.batch_alter_table('other_expenses', schema=None) as batch_op:
        batch_op.drop_column('expense_date')

    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('advance_expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_advance_expenses_project_id')

    op.drop_table('advance_expenses')
    # ### end Alembic commands ###
