"""add sales installments and installment link to sales docs

Revision ID: b24076030b6e
Revises: 3027f74a75f7
Create Date: 2026-03-17 13:57:01.996339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24076030b6e'
down_revision = '3027f74a75f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('percent', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('amount_before_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wht_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billed_at', sa.DateTime(), nullable=True),
    sa.Column('invoiced_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('billing_doc_id', sa.Integer(), nullable=True),
    sa.Column('invoice_doc_id', sa.Integer(), nullable=True),
    sa.Column('receipt_doc_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount_before_tax >= 0', name='ck_sales_installment_base_nonneg'),
    sa.CheckConstraint('gross_total >= 0', name='ck_sales_installment_gross_nonneg'),
    sa.CheckConstraint('installment_no >= 1', name='ck_sales_installment_no_positive'),
    sa.CheckConstraint('net_total >= 0', name='ck_sales_installment_net_nonneg'),
    sa.CheckConstraint('percent >= 0', name='ck_sales_installment_percent_nonneg'),
    sa.CheckConstraint('vat_amount >= 0', name='ck_sales_installment_vat_nonneg'),
    sa.CheckConstraint('wht_amount >= 0', name='ck_sales_installment_wht_nonneg'),
    sa.ForeignKeyConstraint(['billing_doc_id'], ['sales_docs.id'], ),
    sa.ForeignKeyConstraint(['invoice_doc_id'], ['sales_docs.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_docs.id'], ),
    sa.ForeignKeyConstraint(['receipt_doc_id'], ['sales_docs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id', 'installment_no', name='uq_sales_installments_quote_no')
    )
    with op.batch_alter_table('sales_installments', schema=None) as batch_op:
        batch_op.create_index('ix_sales_installments_billing_doc_id', ['billing_doc_id'], unique=False)
        batch_op.create_index('ix_sales_installments_due_date', ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_installments_invoice_doc_id'), ['invoice_doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_installments_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_installments_receipt_doc_id'), ['receipt_doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_installments_status'), ['status'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_sales_doc_id'))
        batch_op.create_index('ix_projects_sales_doc_id', ['sales_doc_id'], unique=False)

    with op.batch_alter_table('sales_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
        batch_op.create_index(batch_op.f('ix_sales_docs_installment_id'), ['installment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_docs_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'sales_installments', ['installment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_docs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_docs_status'))
        batch_op.drop_index(batch_op.f('ix_sales_docs_installment_id'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
        batch_op.drop_column('installment_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_sales_doc_id')
        batch_op.create_index(batch_op.f('ix_projects_sales_doc_id'), ['sales_doc_id'], unique=True)

    with op.batch_alter_table('sales_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_installments_status'))
        batch_op.drop_index(batch_op.f('ix_sales_installments_receipt_doc_id'))
        batch_op.drop_index(batch_op.f('ix_sales_installments_quote_id'))
        batch_op.drop_index(batch_op.f('ix_sales_installments_invoice_doc_id'))
        batch_op.drop_index('ix_sales_installments_due_date')
        batch_op.drop_index('ix_sales_installments_billing_doc_id')

    op.drop_table('sales_installments')
    # ### end Alembic commands ###
