"""add sales installments and installment link to sales docs

Revision ID: de548feba25c
Revises: b24076030b6e
Create Date: 2026-03-26 16:23:40.179433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de548feba25c'
down_revision = 'b24076030b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_sales_doc_id'))
        batch_op.create_index(batch_op.f('ix_projects_sales_doc_id'), ['sales_doc_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_sales_doc_id'))
        batch_op.create_index(batch_op.f('ix_projects_sales_doc_id'), ['sales_doc_id'], unique=False)

    # ### end Alembic commands ###
